services:
  
  adminer:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    container_name: adminer
    networks:
      - net-data
    ports:
      - 6100:8080

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:8.14
    #restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: huynhquocbuu@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    volumes:
       - ./pgadmin4:/var/lib/pgadmin
    ports:
      - 6101:80
    networks:
      - net-data

networks:
  net-data:
    name: net-data
    external: true
    driver: bridge
  net-app:
    name: net-app
    external: true
    driver: bridge