services:
  mysqldb:
    image: mysql:8.0.40-debian
    #restart: unless-stopped
    container_name: mysqldb
    volumes:
      - ./mysqldb:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - net-data
    ports:
      - 3306:3306

networks:
  net-data:
    name: net-data
    external: true
    driver: bridge