services:
  redis:
    image: redis:7.4.1
    container_name: redis
    #restart: unless-stopped
    volumes:
      - ./redis/data:/data
    networks:
      - net-data
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight:2.64.1
    container_name: redisinsight
    #restart: unless-stopped
    networks:
      - net-data
    ports:
      - 6103:8001
    volumes:
      - ./redisinsight/db:/db

networks:
  net-data:
    name: net-data
    external: true
    driver: bridge