services:
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: minio
    ports: 
      - "9000:9000"       # MinIO API port
      - "9001:9001"       # MinIO Console port
    volumes:
      - ./minio:/data
    environment: 
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    networks:
      - net-data

networks:
  net-data:
    name: net-data
    external: true
    driver: bridge