# version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0   # or the latest available
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRESQL_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_DB_URL_HOST: postgresdb
      KC_DB_URL_DATABASE: keycloak
    networks:
      - net-data
    ports:
      - 9085:8080
    command: start-dev --verbose
    # depends_on:
    #   - postgresdb
networks:
  net-data:
    name: net-data
    external: true
    driver: bridge