version: "3.8"
services:
  wiremock:
    image: wiremock/wiremock:3.13.1
    container_name: wiremock
    networks:
      - net-data
    ports:
      - "6109:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files

networks:
  net-data:
    name: net-data
    external: true
    driver: bridge